"use strict";
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const skills=[
{name:"DITA / MSTP",cat:"strategy",level:94,icon:"</>",c:"#9784ff",detail:"Structured content"},{name:"MadCap Flare",cat:"authoring",level:92,icon:"F",c:"#34d5dc",detail:"Online help"},{name:"Adobe RoboHelp",cat:"authoring",level:84,icon:"Rh",c:"#34d5dc",detail:"Help systems"},{name:"Oxygen XML Author",cat:"authoring",level:84,icon:"O₂",c:"#34d5dc",detail:"XML authoring"},{name:"Adobe FrameMaker",cat:"authoring",level:82,icon:"Fm",c:"#34d5dc",detail:"Technical publishing"},{name:"Doc-as-Code",cat:"platform",level:78,icon:"{}",c:"#f59e0b",detail:"Modern workflows"},{name:"Captivate / Camtasia",cat:"learning",level:88,icon:"▶",c:"#e276ed",detail:"eLearning"},{name:"Storyboarding",cat:"learning",level:88,icon:"▦",c:"#e276ed",detail:"Instructional design"},{name:"Video Editing",cat:"learning",level:76,icon:"◉",c:"#e276ed",detail:"After Effects · Audiate"},{name:"GitLab / SourceTree",cat:"platform",level:82,icon:"G",c:"#f59e0b",detail:"Version control"},{name:"AWS / Linux / Ansible",cat:"platform",level:62,icon:"☁",c:"#f59e0b",detail:"Foundational knowledge"},{name:"JIRA / Confluence",cat:"platform",level:86,icon:"J",c:"#f59e0b",detail:"Agile collaboration"},{name:"Information Architecture",cat:"strategy",level:90,icon:"IA",c:"#9784ff",detail:"Content experience"},{name:"AI-assisted Documentation",cat:"strategy",level:88,icon:"AI",c:"#9784ff",detail:"Workflow innovation"},{name:"Release Notes",cat:"strategy",level:94,icon:"RN",c:"#9784ff",detail:"Multi-product delivery"}];
const jobs=[
{role:"Senior Technical Writer",company:"Landis+Gyr",date:"Sep 2022 – Present",place:"Noida",bullets:["Create installation guides, user guides, release notes, and online help for RF Mesh, Mesh IP, and MDM technologies.","Build modular DITA topics aligned with MSTP for field engineers, administrators, and end users.","Developed an AI-assisted release-note solution across products.","Standardized documentation processes and trained SMEs on content workflows.","Create storyboards and eLearning modules with Captivate and Camtasia.","Proposed centralized cloud storage to simplify documentation version control."],tags:["DITA","MSTP","Release Notes","Online Help","AI","eLearning"]},
{role:"Senior Technical Writer",company:"Guavus, a Thales Company",date:"Oct 2020 – Sep 2022",place:"Gurugram",bullets:["Documented telecom analytics solutions including 5G-IQ NWDAF and Service-IQ Device Management Analytics.","Created the first AWS cloud documentation for new projects.","Produced install, operations, troubleshooting, and user guides plus online help with MadCap Flare.","Collaborated with development and QA teams and edited Flare CSS for better HTML output.","Used GitLab for version control and created short videos in Adobe After Effects.","Worked with Cisco and Verizon and revamped a Zendesk Customer Success portal."],tags:["Telecom","MadCap Flare","AWS","GitLab","CSS","Zendesk"]},
{role:"Technical Writer",company:"sa.global",date:"Feb 2019 – Sep 2020",place:"Bengaluru",bullets:["Created process documentation for LexisNexis.","Developed process documentation and user guides for Microsoft Dynamics 365 applications.","Built training manuals and online help using RoboHelp.","Introduced RoboHelp to improve documentation practices.","Presented product and process demonstrations to global stakeholders."],tags:["Dynamics 365","RoboHelp","Process docs","Training","Demos"]}];
const projects=[
{title:"AI Release Notes",short:"AI/RN",cat:"ai",c:"#8b78f5",status:"Developed",desc:"An AI-assisted solution for generating release notes across products, improving efficiency and consistency.",tags:["AI assistance","Release notes","Content operations"]},
{title:"RF Mesh Product Content",short:"MESH",cat:"docs",c:"#18b8c7",status:"Current",desc:"Installation guides, user guides, release notes, and online help for RF Mesh, Mesh IP, and MDM technologies.",tags:["DITA","MSTP","Multi-audience"]},
{title:"eLearning Storyboarding POC",short:"POC",cat:"ai",c:"#d45ddd",status:"Proof of concept",desc:"An AI-assisted storyboarding concept designed to streamline eLearning content development.",tags:["Storyboarding","AI","Instructional design"]},
{title:"Telecom Analytics Docs",short:"5G",cat:"docs",c:"#4c89ef",status:"Delivered",desc:"Cloud and on-premises documentation for 5G-IQ NWDAF and Service-IQ Device Management Analytics.",tags:["MadCap Flare","AWS","Telecom"]},
{title:"Interactive Learning",short:"LEARN",cat:"learning",c:"#ee7abd",status:"Delivered",desc:"Storyboards, eLearning modules, training manuals, product demonstrations, and short-form video content.",tags:["Captivate","Camtasia","RoboHelp"]},
{title:"Customer Portal Experience",short:"CX",cat:"docs",c:"#f59e0b",status:"Revamped",desc:"A redesigned Zendesk Customer Success portal focused on accessibility and improved content discovery.",tags:["Zendesk","Information architecture","UX"]}];
function renderSkills(filter="all",q=""){const list=skills.filter(x=>(filter==="all"||x.cat===filter)&&x.name.toLowerCase().includes(q.toLowerCase()));$("#skills").innerHTML=list.map(x=>`<article class="skill reveal visible" style="--c:${x.c}"><div class="skill-top"><span class="skill-icon">${x.icon}</span><div><h3>${x.name}</h3><small>${x.detail} · ${x.level}%</small></div></div><div class="bar" role="progressbar" aria-valuenow="${x.level}" aria-valuemin="0" aria-valuemax="100" aria-label="Relative emphasis for ${x.name}"><span data-width="${x.level}%"></span></div></article>`).join("");requestAnimationFrame(()=>$$('.bar span').forEach(x=>x.style.width=x.dataset.width));}
function renderJobs(){$("#timeline").innerHTML=jobs.map((j,i)=>`<article class="timeline-item reveal"><span class="dot" aria-hidden="true"></span><div class="job"><button class="job-button" aria-expanded="${i===0}" aria-controls="job-${i}"><div><span class="company">${j.company}</span><h3>${j.role}</h3><p>${j.place}</p></div><span class="job-date">${j.date}<b class="plus">+</b></span></button><div class="job-detail" id="job-${i}"><div><div class="job-content"><ul>${j.bullets.map(b=>`<li>${b}</li>`).join("")}</ul><div class="tags">${j.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div></div></div></div></div></article>`).join("");$$('.job-button').forEach(b=>b.addEventListener('click',()=>b.setAttribute('aria-expanded',String(b.getAttribute('aria-expanded')!=='true'))));}
function renderProjects(filter="all"){const list=projects.filter(p=>filter==="all"||p.cat===filter);$("#projects").innerHTML=list.map(p=>`<article class="project reveal visible" style="--c:${p.c}"><div class="project-visual"><span class="status">${p.status}</span><strong>${p.short}</strong></div><div class="project-body"><span class="badge">${p.cat}</span><h3>${p.title}</h3><p>${p.desc}</p><div class="tags">${p.tags.map(t=>`<span class="tag">${t}</span>`).join("")}</div><div class="project-links">Public repository / demo: not listed</div></div></article>`).join("");}
function theme(){const saved=localStorage.getItem('revathi-theme');const initial=saved||(matchMedia('(prefers-color-scheme:light)').matches?'light':'dark');set(initial);$('.theme').addEventListener('click',()=>set(document.documentElement.dataset.theme==='dark'?'light':'dark'));function set(t){document.documentElement.dataset.theme=t;localStorage.setItem('revathi-theme',t);$('.theme span').textContent=t==='dark'?'☀':'☾';$('.theme').ariaLabel=`Switch to ${t==='dark'?'light':'dark'} theme`;}}
function reveal(){const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(x=>o.observe(x));}
function counters(){const o=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;const x=e.target,n=+x.dataset.target,s=x.dataset.suffix||'';let v=0;const tick=()=>{v=Math.min(n,v+1);x.textContent=v+s;if(v<n)requestAnimationFrame(tick)};tick();o.unobserve(x)}));$$('.counter').forEach(x=>o.observe(x));}
function typing(){if(matchMedia('(prefers-reduced-motion:reduce)').matches)return;const words=['product documentation','online help systems','AI-assisted workflows','learning experiences'];let i=0,j=0,del=false;const el=$('#typed');function tick(){const w=words[i];j+=del?-1:1;el.textContent=w.slice(0,j);let wait=del?45:70;if(!del&&j===w.length){del=true;wait=1450}else if(del&&j===0){del=false;i=(i+1)%words.length;wait=280}setTimeout(tick,wait)}setTimeout(tick,700);}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function ui(){let filter='all';$('#skillFilters').addEventListener('click',e=>{if(!e.target.matches('button'))return;$$('button',e.currentTarget).forEach(b=>b.classList.remove('active'));e.target.classList.add('active');filter=e.target.dataset.filter;renderSkills(filter,$('#skillSearch').value)});$('#skillSearch').addEventListener('input',e=>renderSkills(filter,e.target.value));$('#workFilters').addEventListener('click',e=>{if(!e.target.matches('button'))return;$$('button',e.currentTarget).forEach(b=>b.classList.remove('active'));e.target.classList.add('active');renderProjects(e.target.dataset.work)});const menu=$('.menu'),links=$('#navLinks');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));links.classList.toggle('open',!open)});$$('a',links).forEach(a=>a.addEventListener('click',()=>{links.classList.remove('open');menu.setAttribute('aria-expanded','false')}));$('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('revathi.gollapelli@gmail.com');toast('Email copied')}catch{toast('Select the email to copy it')}});$('#contactForm').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);const subject=encodeURIComponent(d.get('subject'));const body=encodeURIComponent('Hello Revathi,\n\n'+d.get('message')+'\n\nRegards,\n'+d.get('name')+'\n'+d.get('email'));location.href='mailto:revathi.gollapelli@gmail.com?subject='+subject+'&body='+body;$('#formStatus').textContent='Your email application should open now.'});$('#topButton').addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));$('#year').textContent=new Date().getFullYear();}
function scrollUI(){const sections=$$('main section[id]'),nav=$$('.nav-links a');addEventListener('scroll',()=>{const y=scrollY,total=document.documentElement.scrollHeight-innerHeight;$('#progress').style.width=Math.max(0,y/total*100)+'%';$('#header').classList.toggle('scrolled',y>20);$('#topButton').classList.toggle('show',y>700);let current='home';sections.forEach(s=>{if(y>=s.offsetTop-180)current=s.id});nav.forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+current))},{passive:true});}
renderSkills();renderJobs();renderProjects();theme();reveal();counters();typing();ui();scrollUI();
